---
title: Fiscal Year 2018 Recommended Budget
timezone: UTC
collections:
  cabinets:
    title: Cabinets
    output: true
    permalink: "/operating-budget/:collection/:path/"
  categories:
    title: Categories
    output: true
    permalink: "/capital-projects/:path/"
  cp_depts:
    title: Cp Depts
    output: true
    permalink: "/capital-projects/:path/"
  departments:
    title: Departments
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  posts:
    title: Posts
    output: true
  programs:
    title: Programs
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  projects:
    title: Projects
    output: true
    permalink: "/capital-projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: cabinets
  values:
    layout: cabinets
- scope:
    path: ''
    type: departments
  values:
    layout: departments
- scope:
    path: ''
    type: programs
  values:
    layout: programs
- scope:
    path: ''
    type: categories
  values:
    layout: categories
- scope:
    path: ''
    type: cp_depts
  values:
    layout: cp_depts
- scope:
    path: ''
    type: projects
  values:
    layout: projects
email: digital@boston.gov
description: 'Beginning July 1, 2017 and ending June 30, 2018

'
baseurl: ''
url: https://budget.boston.gov
twitter_username: CityOfBoston
github_username: CityOfBoston
markdown: kramdown
exclude:
- node_modules
- package.json
- Gulpfile
- Gemfile
- Gemfile.lock
- vendor
keep_files:
- assets
permalink: "/:collection/:title/"
test:
  post:
  - rake test
include:
- _pages
